blog/urls.py
from django.urls import path, include
# from . import views
from .views import HomeView, CondoDetailView, AddCondoView, UpdateCondoView, DeleteCondoView, submit_review, chart_popup, chart_8071, DeveloperView, DeveloperDetailView, submit_developer_review
from django.conf import settings

urlpatterns = [
    # path('', views.home, name="home"),
    path('', HomeView.as_view(), name="home"),
    path('condo/<int:pk>', CondoDetailView.as_view(), name="condo-info"),
    path('add_condo/', AddCondoView.as_view(), name='add_condo'),
    path('condo/edit/<int:pk>', UpdateCondoView.as_view(), name='update_condo'),
    path('condo/<int:pk>/remove', DeleteCondoView.as_view(), name='delete_condo'),
    path('submit_review/<int:condo_id>/', submit_review, name="submit_review"),
    path('submit_developer_review/<int:developer_id>/', submit_developer_review, name="submit_developer_review"),
    path('chart_popup/', chart_popup, name='chart_popup'),
    path('chart_8071/', chart_8071, name='chart_8071'),
    path('developers/', DeveloperView.as_view(), name="developers"),
    path('developer/<int:pk>', DeveloperDetailView.as_view(), name='developer-detail')
    # path('mortgage_rates/', mortgage_scrape, name='mortgage_rates'),
]

blog_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator

class Author(models.Model):
    name = models.CharField(max_length=100)
    bio = models.TextField()

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title + " | " + str(self.author)

class Developer(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

class Condo(models.Model):
    title = models.CharField(max_length=100)
    condo_image = models.ImageField(null=True, blank=True, upload_to="images/")
    pet_friendly = models.BooleanField()
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    developer = models.ForeignKey(Developer, on_delete=models.CASCADE)
    architect = models.CharField(max_length=255)
    number_of_units = models.IntegerField()
    floors = models.IntegerField()
    built_in = models.IntegerField(
        validators=[
            MaxValueValidator(2100),
            MinValueValidator(1900)
        ]
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('home')


class ReviewRating(models.Model):
    condo = models.ForeignKey(Condo, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    customer_service = models.FloatField()
    build_quality = models.FloatField()
    amenities = models.FloatField()
    location = models.FloatField()
    review_title = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    would_reviewer_recommend = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.review_title

class DeveloperReview(models.Model):
    developer = models.ForeignKey(Developer, on_delete=models.CASCADE, related_name='developer_reviews')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    customer_service = models.FloatField()
    build_quality = models.FloatField()
    amenities = models.FloatField()
    # location = models.FloatField()
    review_title = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    # would_reviewer_recommend = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.review_title

blog/forms.py
from django import forms
from .models import Condo, ReviewRating, DeveloperReview

class CondoForm(forms.ModelForm):
    class Meta:
        model = Condo
        fields = ('__all__')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name of Condo'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

class EditForm(forms.ModelForm):
    class Meta:
        model = Condo
        fields = ('__all__')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name of Condo'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['review_title', 'review', 'customer_service', 'build_quality', 'amenities', 'location', 'would_reviewer_recommend']
        # fields = ('__all__')

class DeveloperReviewForm(forms.ModelForm):
    class Meta:
        model = DeveloperReview
        fields = ['review_title', 'review', 'customer_service', 'build_quality', 'amenities']

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.db.models import Avg, Count
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from .models import Condo, ReviewRating, Developer, DeveloperReview
from .forms import CondoForm, EditForm, ReviewForm, DeveloperReviewForm
from django.urls import reverse_lazy
from django.contrib import messages
from .filters import CondoFilter
from django.core.paginator import Paginator
from django.views.generic.list import MultipleObjectMixin
import json, numpy
import pandas as pd
import requests
from bs4 import BeautifulSoup

# Create your views here.

class DeveloperView(ListView):
    model = Developer
    template_name = 'developers.html'

class DeveloperDetailView(DetailView):
    model = Developer
    template_name = 'developer_details.html'

class HomeView(ListView):
    model = Condo 
    template_name = 'home.html'
    order = ['-id']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        ## Search Functionality
        myFilter = CondoFilter(self.request.GET, queryset=self.get_queryset())
        context['myFilter'] = myFilter

        # Webscraping Functionality
        url = "https://rates.ca/mortgage-rates/british-columbia#brokersandcreditunions"
        response = requests.get(url)
        content = response.content
        soup = BeautifulSoup(content, 'html.parser')
        data = soup.find_all('div', {'class':"richtext-container"})

        mortage_brokers_list = data[2].find_all("ul")

        large_brokerage_list = []
        for li in mortage_brokers_list[0]:
            large_brokerage_list.append(li.text)
        
        context['large_brokerage_list'] = large_brokerage_list
        
        online_brokerage_list = []
        for li in mortage_brokers_list[1]:
            online_brokerage_list.append(li.text)
        
        context['online_brokerage_list'] = online_brokerage_list

        creditunion_list = []
        for li in data[3].find_all("ul")[0]:
            creditunion_list.append(li.text)
        
        context['creditunion_list'] = creditunion_list

        return context
    
class CondoDetailView(DetailView):
    model = Condo
    template_name = 'condo_details.html'

    def get_queryset(self):
        return Condo.objects.prefetch_related('reviews')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        condo = self.get_object()

        ## Paginate condo reviews
        condo_reviews = ReviewRating.objects.filter(condo=condo)
        paginator = Paginator(condo_reviews, 5)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['condo_reviews'] = page_obj
        

        ratings = ReviewRating.objects.filter(condo=condo).aggregate(avg_customer_service=Avg('customer_service'), avg_build_quality=Avg('build_quality'),avg_amenities=Avg('amenities'), avg_location=Avg('location'))
        context['ratings'] = ratings

        ## Pass chart.js context data
        ratings_data = {
            'labels': ['Customer Service', 'Build Quality', 'Amenities', 'Location'],
            'values': [ratings['avg_customer_service'], ratings['avg_build_quality'], ratings['avg_amenities'], ratings['avg_location']]
        }
        ratings_data_json = json.dumps(ratings_data)
        context['ratings_data'] = ratings_data_json

        ## get number of rows, yes-recommendation and no-recommendation
        total_rows = ReviewRating.objects.filter(condo=condo).count()
        context['total_rows'] = total_rows
        number_of_yes = ReviewRating.objects.filter(condo=condo).filter(would_reviewer_recommend="1").count()
        context['number_of_yes'] = number_of_yes
        number_of_no = ReviewRating.objects.filter(condo=condo).filter(would_reviewer_recommend="0").count()
        context['number_of_no'] = number_of_no


        # get most recent review reviews:
        latest_review_object = ReviewRating.objects.filter(condo=condo).order_by('-id')
        if latest_review_object.exists():
            no_probability_list = []
            yes_probability_list = []
            latest_review_object = latest_review_object.first() 
            context['latest_review_object'] = latest_review_object
            last_customer_service_rating = latest_review_object.customer_service
            last_amenities_rating = latest_review_object.amenities
            last_location_rating = latest_review_object.location
            last_build_quality_rating = latest_review_object.build_quality


            ## get customer service probability
            # query formula comes from filtering for the last customer rating, whether reviewers recommend or not and getting a count of number of stars (rows) based on the last customer rating.
            yes_customer_service_probability = ReviewRating.objects.filter(condo=condo).filter(customer_service=last_customer_service_rating).filter(would_reviewer_recommend=1).aggregate(star_count=Count("id"))
            # if condition if number of yes is not 0
            if number_of_yes !=0:
                yes_customer_service_probability = (yes_customer_service_probability['star_count']) / number_of_yes
                context['yes_customer_service_probability'] = yes_customer_service_probability
                yes_probability_list.append(yes_customer_service_probability)
            

            no_customer_service_probability = ReviewRating.objects.filter(condo=condo).filter(customer_service=last_customer_service_rating).filter(would_reviewer_recommend=0).aggregate(star_count=Count("id"))
            # if condition if number of no is not 0
            if number_of_no !=0:
                no_customer_service_probability = (no_customer_service_probability['star_count'])/ number_of_no
                context['no_customer_service_probability'] = no_customer_service_probability
                no_probability_list.append(no_customer_service_probability)

            ## get amenities probability
            yes_amenities_probability = ReviewRating.objects.filter(condo=condo).filter(amenities=last_amenities_rating).filter(would_reviewer_recommend=1).aggregate(star_count=Count("id"))
            if number_of_yes !=0:
                yes_amenities_probability = (yes_amenities_probability['star_count']) / number_of_yes
                context['yes_amenities_probability'] = yes_amenities_probability
                yes_probability_list.append(yes_amenities_probability)

            no_amenities_probability = ReviewRating.objects.filter(condo=condo).filter(amenities=last_amenities_rating).filter(would_reviewer_recommend=0).aggregate(star_count=Count("id"))
            # if condition if number of no is not 0
            if number_of_no != 0:
                no_amenities_probability = (no_amenities_probability['star_count']) / number_of_no
                context['no_amenities_probability'] = no_amenities_probability
                no_probability_list.append(no_amenities_probability)

            ## get location probability
            yes_location_probability = ReviewRating.objects.filter(condo=condo).filter(location=last_location_rating).filter(would_reviewer_recommend=1).aggregate(star_count=Count("id"))
            if number_of_yes !=0:
                yes_location_probability = (yes_location_probability['star_count']) / number_of_yes
                context['yes_location_probability'] = yes_location_probability
                yes_probability_list.append(yes_location_probability)

            no_location_probability = ReviewRating.objects.filter(condo=condo).filter(location=last_location_rating).filter(would_reviewer_recommend=0).aggregate(star_count=Count("id"))
            # if condition if number of no is not 0
            if number_of_no != 0:
                no_location_probability = (no_location_probability['star_count']) / number_of_no
                
                context['no_location_probability'] = no_location_probability
                no_probability_list.append(no_location_probability)

            ## get build quality probabilty 
            yes_build_quality_probability = ReviewRating.objects.filter(condo=condo).filter(build_quality=last_build_quality_rating).filter(would_reviewer_recommend=1).aggregate(star_count=Count("id"))
            
            if number_of_yes !=0:
                context['test2'] = yes_build_quality_probability['star_count']
                yes_build_quality_probability = (yes_build_quality_probability['star_count']) / number_of_yes
                context['yes_build_quality_probability'] = yes_build_quality_probability
                yes_probability_list.append(yes_build_quality_probability)

            no_build_quality_probability = ReviewRating.objects.filter(condo=condo).filter(build_quality=last_build_quality_rating).filter(would_reviewer_recommend=0).aggregate(star_count=Count("id"))
            # if condition if number of no is not 0
            if number_of_no != 0:
                no_build_quality_probability = (no_build_quality_probability['star_count']) / number_of_no

                context['no_build_quality_probability'] = no_build_quality_probability
                no_probability_list.append(no_build_quality_probability)

            yes_probability = number_of_yes/total_rows
            context['yes_probability'] = yes_probability
            yes_probability_list.append(yes_probability)

            no_probability = number_of_no/total_rows
            context['no_probability'] = no_probability
            no_probability_list.append(no_probability)

            # yes_probability_list = [yes_customer_service_probability, yes_amenities_probability, yes_location_probability, yes_build_quality_probability, yes_probability]

blog/templates/add_condo.html
{% extends 'base.html'%}
{% block title %}Add a New Condominium{% endblock %}
{% block content %}

<h1>Add Condo</h1>
<br>
<br>

<div class="form-group">
    <form method="POST", enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Post</button>
</div>



{% endblock %}

blog/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Rate My  Condo {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">Rate my Condo</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <!-- <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li> -->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'add_condo' %}">Add Condo</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'developers' %}">Developers</a>
              </li>
              <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li> -->
            </ul>
            <!-- <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form> -->
          </div>
        </div>
      </nav>
    <br>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.7.1/dist/chart.min.js"></script>
  </body>
</html>

blog/templates/chart_8071.html
<!DOCTYPE html>
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>

    <title>My Template</title>
</head>
<body>
    <!-- {% block content %}
    <div id="chart-container">
        <canvas id="my-chart"></canvas>
    </div>

    <script>
        var chartData = {{ data|safe }};
    </script>
    {% endblock %} -->
    <h1>{{ message }}</h1>
    <canvas id="myChart"></canvas>

    <script>
        var data = {{ data|safe }};
        var ctx = document.getElementById('myChart').getContext('2d');
        var chart = new Chart(ctx, {
          type: 'line',
          data: {
            labels: data.map(function(row) { return row.date; }),
            datasets: [{
              label: 'Data',
              data: data.map(function(row) { return row.value; }),
              backgroundColor: 'rgba(0, 119, 204, 0.3)',
              borderColor: 'rgba(0, 119, 204, 1)',
              borderWidth: 1
            }]
          },
          options: {
            responsive: true,
            maintainAspectRatio: false,
            scales: {
              yAxes: [{
                ticks: {
                  beginAtZero: true
                }
              }]
            }
          }
        });
      </script>
    <!-- {%for row in data%}
    <tr>
        <td> {{row.columns1}}</td>
        <td> {{row.columns2}}</td>
        <td> {{row.columns3}}</td>
    </tr>
        
    {% endfor %} -->
    
</body>

</html>

blog/templates/condo_details.html
{% extends 'base.html'%}
{% block title %} {{condo.title}}{% endblock %}
{% block content %}

<script>
    var m = document.getElementsByClassName("alert");  // Return an array

    setTimeout(function(){
    if (m && m.length) {
        m[0].classList.add('hide');
    }
    }, 1000);

    function openChartWindow() {
        // Get ratings data from context
        const ratingsData = "{{ ratings_data|escapejs }}";
        
        // Parse ratings data as JSON
        const ratings = JSON.parse(ratingsData);
        // Define the URL of the chart popup window
        const url = "{% url 'chart_popup' %}";

        // Open the pop-up window
        const chartWindow = window.open(url, '_blank', 'width=600,height=400');

        // When the pop-up window is loaded, pass the chart data to it
        chartWindow.addEventListener('load', function() {
            var label = ratings.labels
            var data = ratings.values
            chartWindow.postMessage({label: label, data: data}, "*");
        });
    }
</script>

<h1>{{ condo.title }}</h1>
<br>
<br>
{% if condo.condo_image %}
    <img src="{{ condo.condo_image.url}}"><br><br>
{% endif %}
<br>
Pet Friendly:{% if condo.pet_friendly %} Yes {%else %} No {% endif %}
<br>
Built In: {{condo.built_in}}
<br>
Number of units: {{condo.number_of_units}} | {{condo.floors}} stories
<br>
Developer: {{condo.developer}} | Artchitect: {{condo.architect}}
<br>
<small>
    <a href="{% url 'update_condo' condo.pk %}">Edit</a>
    <a href="{% url 'delete_condo' condo.pk %}">Delete</a>
</small>

<p> Averge of customer service rating: {{ratings.avg_customer_service}} </p>
<p> Averge of build quality rating: {{ratings.avg_build_quality}} </p>
<p> Averge of amenities rating: {{ratings.avg_amenities}} </p>
<p> Averge of location rating: {{ratings.avg_location}} </p>
<button id="chart-btn" onclick="openChartWindow()">Show Ratings Chart</button>
<p> total number of rows: {{total_rows}} </p>
<p> number of yes's: {{number_of_yes}} </p>
<p> number of no's: {{number_of_no}} </p> 
<br>
<p>most recent review. Customer service: {{latest_review_object.customer_service}}</p>
<p>most recent review. amenities: {{latest_review_object.amenities}}</p>
<p>most recent review. build quality: {{latest_review_object.build_quality}}</p>
<p>most recent review. location: {{latest_review_object.location}}</p>

<p>test2: {{test2}}</p>

<p> YES customer service 1-star probability: {{yes_customer_service_probability}} </p>
<p>NO customer service probability: {{no_customer_service_probability}}</p>
<p> YES amenities 1-star probability: {{yes_amenities_probability}} </p> 
<p> NO amenities 1-star probability: {{no_amenities_probability}} </p> 
<p> YES locations probability: {{yes_location_probability}} </p> 
<p> NO locations probability: {{no_location_probability}} </p> 
<p> YES build quality 1-star probability: {{yes_build_quality_probability}} </p> 
<p> NO build quality 1-star probability: {{no_build_quality_probability}} </p> 
<p>yes cus service probability: {{test1}}</p>
<p>total YEs probability: {{yes_probability}}</p>
<p>total NO probability: {{no_probability}}</p>
<p>value rating: {{value_rating}}</p>



<form action="{% url 'submit_review' condo.pk %}" method="POST">
    <br><br>
    {% csrf_token %}
    <h5>Write Your Review</h5>
    <div>
        <!--- Rating stars-->
        <div class ="test">
            <label>Rate Customer Service</label>
            <br>
            <div class="rate">
                <input type="radio" name="customer_service" id="customer_service-rating5" value="5" required /><label for="customer_service-rating5" title="5"></label>
                <input type="radio" name="customer_service" id="customer_service-rating4" value="4" required /><label for="customer_service-rating4" title="4"></label>
                <input type="radio" name="customer_service" id="customer_service-rating3" value="3" required /><label for="customer_service-rating3" title="3"></label>
                <input type="radio" name="customer_service" id="customer_service-rating2" value="2" required /><label for="customer_service-rating2" title="2"></label>
                <input type="radio" name="customer_service" id="customer_service-rating1" value="1" required /><label for="customer_service-rating1" title="1"></label>
            </div>
        </div>
        <div class ="test">
            <label>Rate Build Quality</label>
            <br>
            <div class="rate">
                <input type="radio" name="build_quality" id="build_quality-rating5" value="5" required /><label for="build_quality-rating5" title="5"></label>
                <input type="radio" name="build_quality" id="build_quality-rating4" value="4" required /><label for="build_quality-rating4" title="4"></label>
                <input type="radio" name="build_quality" id="build_quality-rating3" value="3" required /><label for="build_quality-rating3" title="3"></label>
                <input type="radio" name="build_quality" id="build_quality-rating2" value="2" required /><label for="build_quality-rating2" title="2"></label>
                <input type="radio" name="build_quality" id="build_quality-rating1" value="1" required /><label for="build_quality-rating1" title="1"></label>
            </div>
        </div>
        <div class ="test">
            <label>Rate Build Amenities</label>
            <br>
            <div class="rate">
                <input type="radio" name="amenities" id="amenities-rating5" value="5" required /><label for="amenities-rating5" title="5"></label>
                <input type="radio" name="amenities" id="amenities-rating4" value="4" required /><label for="amenities-rating4" title="4"></label>
                <input type="radio" name="amenities" id="amenities-rating3" value="3" required /><label for="amenities-rating3" title="3"></label>
                <input type="radio" name="amenities" id="amenities-rating2" value="2" required /><label for="amenities-rating2" title="2"></label>
                <input type="radio" name="amenities" id="amenities-rating1" value="1" required /><label for="amenities-rating1" title="1"></label>
            </div>
        </div>
        
        <div class ="test">
            <label>Rate Location</label>
            <br>
            <div class="rate">
                <input type="radio" name="location" id="location-rating5" value="5" required /><label for="location-rating5" title="5"></label>
                <input type="radio" name="location" id="location-rating4" value="4" required /><label for="location-rating4" title="4"></label>
                <input type="radio" name="location" id="location-rating3" value="3" required /><label for="location-rating3" title="3"></label>
                <input type="radio" name="location" id="location-rating2" value="2" required /><label for="location-rating2" title="2"></label>
                <input type="radio" name="location" id="location-rating1" value="1" required /><label for="location-rating1" title="1"></label>
            </div>
        </div>
        
        <br>
        Review Title:
        <input name="review_title" type="text" class="form-control">
        <br>
        Review:
        <textarea name="review" rows="4" class="form-control"></textarea>
        <br>
        <input type="submit" value="Submit Review" class="btn btn-primary">
        <br>
        Would Reviewer Recommend?
        <br>
        <!-- <select name="would_reviewer_recommend">
            <option value="1" {% if condo.would_reviewer_recommend %}selected {% endif %}>Yes</option>
            <option value="0">No</option>
        </select> -->
        <label>
            <input type="checkbox" name="would_reviewer_recommend" value="yes" {% if condo.would_reviewer_recommend%}checked{% endif %}>
            Yes
        </label>
    </div>
    {% include 'includes/alerts.html' %}
</form>
<br>
<header class="section-heading">
    <h3>Customer Reviews</h3>
    <ul>
    {% for review in condo_reviews %}
        {{ review.review_title }}<br>
        {{ review.review }}<br>
        {{ review.customer_service }}<br>
        {{ review.build_quality }}<br>
        {{ review.amenities }}<br>
        {{ review.location }}
        <hr>
    {% endfor %}
    {% if condo_reviews.has_previous %}
        <a href="?page={{ condo_reviews.previous_page_number }}">previous</a>
    {% endif %}
    {% for page_number in condo_reviews.paginator.page_range %}
    {% if condo_reviews.number == page_number %}
        <span>{{ page_number }}</span>
    {% else %}
        <a href="?page={{ page_number }}">{{ page_number }}</a>
    {% endif %}
    {% endfor %}

    {% if condo_reviews.has_next %}
        <a href="?page={{ condo_reviews.next_page_number }}">next</a>
    {% endif %}
    </ul>
    
</header>

{% endblock %}

blog/templates/delete_condo.html
{% extends 'base.html'%}
{% block title %}Delete Condo{% endblock %}
{% block content %}

<h1>Delete Condo</h1>
<br>
<br>
<h3>Delete: {{condo.title}}</h3>
<br>
<div class="form-group">
    <form method="POST", enctype="multipart/form-data">
        {% csrf_token %}
        <strong>Are you Sure?</strong><br><br>
        <button>Delete Condo</button>
</div>



{% endblock %}

blog/templates/developers.html
{% extends 'base.html'%}
{% block content %}

<h1>Developers</h1>
{% for developer in object_list %}
    <a href="{% url 'developer-detail' developer.pk %}">{{developer.title}}</a>
    {% for condo in developer.condo_set.all %}
        <li> <a href="{% url 'condo-info' condo.pk %}">{{condo.title}} </a></li>
    {% endfor %}
<hr>
{% endfor %}

{% endblock %}